
###    GET all users
GET http://localhost:3000/api/users

###    POST user  (all fields)
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "first_name": "Rei",
    "last_name": "Ro",
    "email": "reinis123456@gmail.com",
    "password": "123456"
}

###    GET user    /api/users/:id
GET http://localhost:3000/api/users/1

###    DELETE user    /api/users/:id
DELETE http://localhost:3000/api/users/17

###    EDIT user    /api/users/:id   +   all fields
PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
    "first_name": "Reinis",
    "last_name": "Vāravs",
    "email": "reinis@gmail.com",
    "password": "1234"
}

### LOGIN USER
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "reinis@gmail.com",
    "password": "1234"
}

### Logout User
POST http://localhost:3000/logout
